apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: ping
  name: ping
spec:
  containers:
  - args:
    - "3000"
    command:
    - sleep
    image: alpine
    name: ping
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
