apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: task0pod
  name: task0pod
  namespace: mynamespace
spec:
  containers:
  - image: nginx
    name: task0pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
